---

- name: Install docker
  package:
    name: docker
    state: present
  ignore_errors: yes

- name: Make sure docker is running
  systemd:
    state: started
    name: docker

- name: Setup docker dir
  file:
    path: ~/.docker
    state: directory

- name: Docker login
  get_url:
    url: "{{ docker_config_url }}"
    dest: ~/.docker/config.json
    force: yes

- name: Add olm crd
  command: kubectl apply -f {{ olm_crd_url }}
  register: olm_crd_status
  until: olm_crd_status.rc == 0
  delay: 5
  retries: 10
  ignore_errors: yes
  tags: [olm]

- name: Add olm
  command: kubectl apply -f {{ olm_url }}
  register: olm_status
  until: olm_status.rc == 0
  delay: 5
  retries: 10
  ignore_errors: yes
  tags: [olm]

- name: Add pull secret for registry.connect.redhat.com
  get_url:
    url: "{{ pull_secret_url }}"
    dest: "{{ pull_secret_destination }}"
    mode: 0755
    force: yes

- name: Download operator-sdk binary
  get_url:
    url: "https://github.com/operator-framework/operator-sdk/releases/download/{{operator_sdk_version}}/operator-sdk-{{operator_sdk_version}}-x86_64-linux-gnu"
    dest: /usr/local/bin/operator-sdk
    force: yes
    mode: u=rwx,g=xr,o=x
  tags: [sdk]
